### ISSUE TITLE
UriException: Namespace missing from extends class.

### ISSUE THREAD

**Issue by apapsch** [thephpleague/uri-schemes#5]
https://github.com/thephpleague/uri-schemes/blob/fd2448689186bfff27a112aa21d82931f4b366c5/src/UriException.php#L26

Exception doesn't exist in the current namespace. My quick fix was adding a backslash to Exception.

**Comment by nyamsprod** [comment]
@apapsch yes Exception exists since this package require Uri-parser and Exception is defined in Uri Parser package see https://github.com/thephpleague/uri-parser/blob/master/src/Exception.php  👍
