### ISSUE TITLE
Should we reduce PSR-7 compatibility ?

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri-schemes#9]
In version 1.x  all URI object implements the `League\Uri\Interfaces\Uri` interface which is a generalize version of `PSR-7` `UriInterface`. For version 2.x I'm thinking of further moving away of the PSR-7 interface while keeping the same public API.

The main problem with the current interface is that getters and setters always return or expect a `string`. This leads to the fact that you can not make any type of difference between a URI component whose content is the empty string and one which is not defined and whose content is expected to be `null`.  

While it can be debatable if this behavior is even sane in regards to PSR-7 for a general purpose URI package I think no making this distinction is wrong. 

My thought for version 2.0 is to allow nullable string (ie `?string`) for getter/setters. In consequence the `Http` class will no longer implements PSR-7 `UriInterface`. 

Thoughts ? @kelunik

**Comment by kelunik** [comment]
I'm not sure. For Aerys we wanted to rely on the `UriInterface` or PSR-7, even if it's annoying to pull in PSR-7 just for that. @trowski thoughts?

**Comment by nyamsprod** [comment]
@kelunik I understand your reservations... maybe we could keep a PSR7 compatible class in the package called PSR7Uri or something ? 

The goal is to be able to distinguish this

```php
<?php

echo Http::createFromString('http://example.com?foo=bar')->withQuery('');
//should return 'http://example.com?'
//vs
echo Http::createFromString('http://example.com?foo=bar')->withQuery(null);
//should return 'http://example.com'
```
This distinction may be a edge-case for the HTTP URI but that's no the case for every URI. For instance the empty string host mean an invalid URI for the HTTP URI while it makes perfect sense for LDAP URI or File URI.

**Comment by trowski** [comment]
@nyamsprod You can add nullability to a type and still fulfill the interface contract. So `withQuery(?string $query = null)` is compatible with `withQuery(string $query)`, therefore can still implement `UriInterface`.

@kelunik I still have mixed feelings on pulling in PSR-7 in Aerys because it's only used for URIs. However, it is nice to use an accepted API where we can replace the implementation at will without BC breaks. This package has a URI interface as well, perhaps we should rely on that? Splitting another package off as a uri-psr7 makes sense, since there's no reason for this lib to require all of PSR-7. Then users can require that package if they need PSR-7 compatibility.

**Comment by nyamsprod** [comment]
@trowski yes nullable type can be added to the parameter but not on the method return type which is expected to always be a string.

**Comment by trowski** [comment]
@nyamsprod D'oh, totally forgot about the return type. Yeah, then IMO it would be best to put a PSR-7 compatibility shim into a separate package.

**Comment by nyamsprod** [comment]
@trowski @kelunik 
I've made the following changes in the [develop branch](https://github.com/thephpleague/uri-schemes/tree/develop) which are the following:

- I've removed the `Data`, `File`, `Ftp`, `Ws` classes all their specific URI validation are now part of the URI class;

- the `Uri` class is now final and does not exposes any League Uri Interfaces (this may or may not change in the future). While its getter/setter methods are similar to PSR-7 `UriInterface` it differs in that it's getter method can return null or a string and its setter method also accepts the `null` value.

- the `Http` class is a PSR-7 `UriInterface` implementing class but it is no longer restricted to the HTTP(S) schemes. It is now build using the `Uri` class via composition and not via inheritance.

- Last but not least, the `Factory` class picks up all the static named creator methods from the removed classes and allows the instantiation of URI objects or PSR-7 UriInterface objects.

This should remove the need to create a shim into a separate package like @trowski suggested. It gives two classes to interact with URI with their respective pro/cons. So depending on the need of the developper is may choose the PSR-7 implementation or a more Generic implementations.

- the `Uri` class is a generic RFC3986 compliant URI object. Non scheme URI won't be treated as if they were HTTP URI but as generic URI (which have different validation rules);
- the `Http` class is a PSR-7 UrinInterface implementions with a Http(s) URI first orientation. so it will treat non scheme URI as if they were HTTP URI thus preventing URI like `///path` to be validated. Also as it follow PSR-7, only string (or stringable) value are allowed are argument for the setter methods.


So in any given project one would use the `Uri` class or the `Http` one. Using both at the same time should be only made by experimented users who understand the difference between both classes ?

What do you think ?

Here's an illustration of the differences:
as an example:

```php

use League\Uri\Uri;
use League\Uri\Http;

$uri = Uri::createFromString('https://example.com/path#fragment'); //will work
$http = new Http($uri); //you can create an Http URI from a Uri;

$uri->withPort(70000); // will work;
$http->withPort(70000); // will throw an InvalidArgumentException because PSR-7 does not allow port > 65535
```

**Comment by nyamsprod** [comment]
the solution is now merge into the master branch as described
